site_name: NEI_Documentation
nav:
  - Home: index.md
  - API: API.md
  - Developer: DEVELOPER.md
  - Code_of_Condute: CODE_OF_CONDUCT.md
  - Seniors: Seniors.md
  - Admin: ADMIN.md
theme:
  name: mkdocs
  nav_style: dark
